# Generated by Django 4.2.6 on 2023-11-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mieszkaniec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_utworzenia", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
