# Generated by Django 4.2.6 on 2023-11-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telefony", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mieszkaniec",
            name="administracja",
            field=models.CharField(
                choices=[("NS", "NS"), ("NW", "NW"), ("CE", "CE")],
                default="CE",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="mieszkaniec",
            name="adres",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mieszkaniec",
            name="indeks",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="mieszkaniec",
            name="klatka",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="mieszkaniec",
            name="nazwa",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mieszkaniec",
            name="telefon",
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name="mieszkaniec",
            name="zgoda",
            field=models.CharField(
                choices=[("tak", "tak"), ("nie", "nie")], default="tak", max_length=3
            ),
        ),
    ]
