# Generated by Django 4.2.6 on 2023-11-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telefony", "0002_mieszkaniec_administracja_mieszkaniec_adres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mieszkaniec",
            name="content",
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="mieszkaniec",
            name="phone",
            field=models.TextField(blank=True, max_length=9),
        ),
    ]
