# Generated by Django 4.2.6 on 2023-11-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_utworzenia", models.DateTimeField(auto_now_add=True)),
                ("powod", models.TextField(max_length=500)),
                ("dotyczy", models.TextField(max_length=1000)),
                ("data_pozew", models.DateTimeField(blank=True)),
                ("wyrok1", models.TextField(blank=True, max_length=1000)),
                ("wyrok2", models.TextField(blank=True, max_length=1000)),
                ("egzekucja", models.TextField(blank=True, max_length=1000)),
                ("uwagi", models.TextField(blank=True, max_length=2000)),
                ("zakonczenie", models.TextField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Zakonczono", "Zakonczono"),
                            ("W trakcie realizacji", "W trakcie realizacji"),
                        ],
                        default="Zakonczono",
                        max_length=22,
                    ),
                ),
            ],
        ),
    ]
