# Generated by Django 4.2.6 on 2023-11-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="content",
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="record",
            name="phone",
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
