# Generated by Django 4.2.6 on 2023-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0002_record_content_record_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="phone",
            field=models.PositiveIntegerField(),
        ),
    ]
