# Generated by Django 4.2.6 on 2023-11-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0004_alter_record_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="content",
        ),
        migrations.RemoveField(
            model_name="record",
            name="phone",
        ),
    ]
