# Generated by Django 4.2.6 on 2023-11-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0005_remove_record_content_remove_record_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="status",
            field=models.CharField(
                choices=[(1, "Zakonczono"), (2, "W trakcie realizacji")], max_length=22
            ),
        ),
    ]
