# Generated by Django 4.2.6 on 2023-11-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0006_alter_record_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="status",
            field=models.CharField(
                choices=[
                    ("Zakonczono", "Zakonczono"),
                    ("W trakcie realizacji", "W trakcie realizacji"),
                ],
                default="Zakonczono",
                max_length=22,
            ),
        ),
    ]
