# Generated by Django 4.2.6 on 2023-11-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0007_alter_record_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="data_pozew",
            field=models.DateField(blank=True),
        ),
    ]
