# Generated by Django 4.2.6 on 2023-11-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0011_alter_record_data_pozew"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="kto",
            field=models.CharField(
                choices=[
                    ("Zakonczono", "Zakonczono"),
                    ("W trakcie realizacji", "W trakcie realizacji"),
                ],
                default="Przeciwko",
                max_length=22,
            ),
        ),
    ]
