# Generated by Django 4.2.6 on 2023-11-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0012_record_kto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="kto",
            field=models.CharField(
                choices=[("Przeciwko", "Przeciwko"), ("Przez", "Przez")],
                default="Przeciwko",
                max_length=22,
            ),
        ),
    ]
