# Generated by Django 4.2.6 on 2023-11-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0014_record_content_record_phone_alter_record_kto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="phone",
            field=models.CharField(
                choices=[
                    ("500524230", "Asystentka"),
                    ("601521658, 601202139", "Zarzad"),
                    ("694704533", "Radca"),
                    ("601521657", "IT"),
                    ("601521658, 601202139, 500524230, 694704533", "Wszyscy"),
                ],
                default="601521658, 601202139",
                max_length=100,
            ),
        ),
    ]
