# Generated by Django 4.2.6 on 2023-11-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0015_alter_record_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="content",
            field=models.TextField(blank=True, max_length=160),
        ),
    ]
