# Generated by Django 4.2.6 on 2023-11-08 08:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0016_alter_record_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="dotyczy",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
