# Generated by Django 4.2.6 on 2023-11-13 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0016_alter_record_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="data_upload",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 11, 13, 20, 45, 38, 609855, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="record",
            name="opis",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="record",
            name="plik",
            field=models.FileField(blank=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="record",
            name="dotyczy",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="record",
            name="kto",
            field=models.CharField(
                choices=[
                    ("Pozew przeciwko Spółdzielni", "Pozew przeciwko Spółdzielni"),
                    ("Pozew przez Spółdzielnię", "Pozew przez Spółdzielnię"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="powod",
            field=models.CharField(max_length=500),
        ),
    ]
