# Generated by Django 4.2.6 on 2023-11-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0017_alter_record_dotyczy"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="snippet",
            field=models.TextField(default="codding", max_length=1000),
        ),
    ]
