# Generated by Django 4.2.7 on 2023-11-30 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0017_record_data_upload_record_opis_record_plik_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='data_upload',
        ),
        migrations.RemoveField(
            model_name='record',
            name='opis',
        ),
        migrations.RemoveField(
            model_name='record',
            name='plik',
        ),
        migrations.CreateModel(
            name='Plik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(blank=True, max_length=255)),
                ('plik', models.FileField(blank=True, upload_to='uploads/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('podmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.record')),
            ],
        ),
    ]
