# Generated by Django 4.2.7 on 2023-11-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0018_remove_record_data_upload_remove_record_opis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='opis',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='record',
            name='plik',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='Plik',
        ),
    ]
