# Generated by Django 4.2.6 on 2023-11-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0018_record_snippet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="snippet",
        ),
    ]
