# Generated by Django 4.2.6 on 2023-11-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0019_remove_record_snippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="dotyczy",
            field=models.TextField(max_length=1000),
        ),
    ]
