# Generated by Django 4.2.7 on 2023-12-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0019_record_opis_record_plik_delete_plik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='data_pozew',
            field=models.DateField(blank=True, null=True),
        ),
    ]
