# Generated by Django 4.2.6 on 2023-11-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0020_alter_record_dotyczy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="dotyczy",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="record",
            name="powod",
            field=models.CharField(max_length=500),
        ),
    ]
