# Generated by Django 4.2.6 on 2023-11-10 15:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0021_alter_record_dotyczy_alter_record_powod"),
    ]

    operations = [
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tytul", models.CharField(max_length=100)),
                (
                    "file",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="file"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="record",
            name="kto",
            field=models.CharField(
                choices=[
                    ("Pozew przeciwko Spółdzielni", "Pozew przeciwko Spółdzielni"),
                    ("Pozew przez Spółdzielnię", "Pozew przez Spółdzielnię"),
                ],
                max_length=50,
            ),
        ),
    ]
