# Generated by Django 4.2.7 on 2023-12-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0021_alter_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='data_pozew',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
