# Generated by Django 4.2.6 on 2023-11-12 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0022_storage_alter_record_kto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Storage",
        ),
        migrations.AddField(
            model_name="record",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="record",
            name="document",
            field=models.FileField(blank=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="record",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
