# Generated by Django 4.2.7 on 2023-12-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0023_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.AlterField(
            model_name='record',
            name='plik',
            field=models.FileField(upload_to=''),
        ),
    ]
